### PR TITLE
fix(spotlight): Prevent feedback loop when SENTRY_SPOTLIGHT points to self

### LINKED ISSUE #1062: Spotlight crashes due to a memory leak when ran using non-npm package manager
### Environment

node v20.19.3
spotlight 4.3.1

### Steps to Reproduce

Run: `pnpx @spotlightjs/spotlight@latest -p $SENTRY_SPOTLIGHT_PORT`

Got this:

<details>
 <summary>V8 Logs for crash</summary>

```sh
➜  pnpx @spotlightjs/spotlight@latest -p $SENTRY_SPOTLIGHT_PORT
Downloading @spotlightjs/overlay@4.3.1: 10.32 MB/10.32 MB, done
Packages: +189
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 189, reused 169, downloaded 20, added 189, done
🔎 [Spotlight] Spotlight by Sentry - v{unknown}
🔎 [Spotlight] Sidecar listening on 5001
🔎 [Spotlight] Open http://localhost:5001 to see the Spotlight UI

<--- Last few GCs --->

[7325:0x160008000]   200720 ms: Mark-Compact 3363.7 (4128.6) -> 3350.8 (4131.3) MB, 158.42 / 0.00 ms  (average mu = 0.333, current mu = 0.317) allocation failure; scavenge might not succeed
[7325:0x160008000]   200925 ms: Mark-Compact 3367.9 (4131.6) -> 3356.0 (4131.3) MB, 191.79 / 0.00 ms  (average mu = 0.210, current mu = 0.065) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0x1025b55b8 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 2: 0x102773968 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 3: 0x1029817bc v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 4: 0x1029852b8 v8::internal::Heap::CollectGarbageShared(v8::internal::LocalHeap*, v8::internal::GarbageCollectionReason) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 5: 0x102982134 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 6: 0x10297fcb0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 7: 0x102975fc0 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 8: 0x102976818 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
 9: 0x10295a5a8 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
10: 0x1029505dc v8::internal::MaybeHandle<v8::internal::SeqTwoByteString> v8::internal::FactoryBase<v8::internal::Factory>::NewRawStringWithMap<v8::internal::SeqTwoByteString>(int, v8::internal::Map, v8::internal::AllocationType) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
11: 0x10295c98c v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<unsigned char const> const&, unibrow::Utf8Variant, v8::internal::AllocationType) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
12: 0x10295cb90 v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
13: 0x1027968dc v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
14: 0x1026a6194 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
15: 0x10258c628 void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
16: 0x103075ef0 Builtins_CallApiCallback [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
17: 0x108263a3c
18: 0x1080718c4
19: 0x107e283dc
20: 0x107f31d98
21: 0x107c64ba4
22: 0x107eab4d8
23: 0x10307250c Builtins_JSEntryTrampoline [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
24: 0x1030721f4 Builtins_JSEntry [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
25: 0x1028ec274 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
26: 0x1028ebb08 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
27: 0x10278f998 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
28: 0x1024ccd5c node::InternalCallbackScope::Close() [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
29: 0x1024ccfb4 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
30: 0x1024e130c node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
31: 0x1025d97f8 node::(anonymous namespace)::Parser::OnStreamRead(long, uv_buf_t const&) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
32: 0x1026a4380 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
33: 0x1026a4a98 node::LibuvStreamWrap::ReadStart()::$_1::__invoke(uv_stream_s*, long, uv_buf_t const*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
34: 0x10305bf44 uv__stream_io [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
35: 0x103063bd0 uv__io_poll [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
36: 0x103051490 uv_run [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
37: 0x1024cd7e8 node::SpinEventLoopInternal(node::Environment*) [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
38: 0x1025f9eec node::NodeMainInstance::Run() [[redacted]/.local/share/fnm/node-versions/v20.19.3/installation/bin/node]
39: 0x102577cfc node::Start(int, char**) [[redacted]/.local/share/fnm/n ode-versions/v20.19.3/installation/bin/node]
40: 0x185ecab98 start [/usr/lib/dyld]
 ERROR  Command was killed with SIGABRT (Aborted): spotlight -p 5001

pnpm: Command was killed with SIGABRT (Aborted): spotlight -p 5001
    at makeError ([redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:15561:17)
    at handlePromise ([redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:16132:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] ([redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:189259:9)
    at async [redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:200166:23
    at async main ([redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:200124:34)
    at async runPnpm ([redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:200391:5)
    at async [redacted]/.local/share/fnm/node-versions/v20.19.3/installation/lib/node_modules/pnpm/dist/pnpm.cjs:200383:7

```
</details>

### PR DESCRIPTION
**Pull request by BYK**
Fixes #1062

## Problem

When users set the `SENTRY_SPOTLIGHT` environment variable to point to the same Spotlight instance they're running, it creates an infinite feedback loop where Spotlight sends its own telemetry to itself, causing memory exhaustion and crashes.

## Solution

This PR adds intelligent detection to prevent the feedback loop by:

- **Using sidecar's CLI parser**: Leverages `parseCLIArgs()` from `@spotlightjs/sidecar/cli` to accurately detect the instance port
- **Smart URL parsing**: Parses `SENTRY_SPOTLIGHT` to determine the target URL and compares it with the running instance
- **Truthy value handling**: Handles truthy values (`true`/`1`) which indicate using the default URL (localhost:8969)
- **Localhost-only protection**: Only disables spotlight integration when the target is localhost AND ports match
- **Non-defensive approach**: Errs on the side of no action - invalid URLs are silently ignored without warnings
- **Dynamic port limitation**: Documents in code comments that port 0 (dynamic assignment) cannot be protected

## Changes

- Modified `packages/spotlight/bin/instrument.js` to detect and prevent self-referencing feedback loops
- Only sets `spotlight: false` in SDK init when a confirmed feedback loop is detected
- Clear warning message shown to users when the loop is prevented

## Testing

Verified across multiple scenarios:
- ✅ No env var → Works normally
- ✅ Truthy value with default port → Disables with warning
- ✅ Truthy value with different port → Works normally  
- ✅ Full URL with matching port → Disables with warning
- ✅ Full URL with different port → Works normally
- ✅ Invalid/unparseable values → Works normally, no warnings
- ✅ Dynamic port assignment → Works normally (limitation documented)

### CODE REVIEW

File: packages/spotlight/bin/instrument.js [hunk 1]
```diff
@@ -1,4 +1,56 @@
...
+
+// Check if SENTRY_SPOTLIGHT points to this instance
+const spotlightEnv = process.env.SENTRY_SPOTLIGHT;
+let disableSpotlight = false;
+
+// Note: If port is set to 0 (dynamic port assignment), we cannot detect the actual port
+// before starting the server, so we cannot prevent the feedback loop in that case.
+// The server will be assigned a port by the OS after it starts, and if SENTRY_SPOTLIGHT
+// happens to point to that same port, a feedback loop may occur.
+if (spotlightEnv && instancePort !== 0) {
```
[the remark this answers is not in the document]
Comment (BYK) [reply packages/spotlight/bin/instrument.js:16]: Intentional

File: packages/spotlight/bin/instrument.js [hunk 2]
```diff
@@ -1,4 +1,56 @@
...
+  let targetPort;
+  let targetHost;
+
+  // SENTRY_SPOTLIGHT can be:
+  // 1. A full URL like "http://localhost:8969"
+  // 2. A truthy value (true, t, y, yes, on, 1) which means use the default URL
+  const TRUTHY_ENV_VALUES = new Set(["true", "t", "y", "yes", "on", "1"]);
```
Comment (betegon) [inline packages/spotlight/bin/instrument.js:23]: i don't know how  SENTRY_SPOTLIGHT can be all those things but ok

File: packages/spotlight/bin/run.js [hunk 3]
```diff
@@ -20,55 +20,44 @@ const homeDir = process.env.HOME || process.env.USERPROFILE;
...
-      );
+    startSpan({ name: "Setup Server Assets", op: "cli.setup.sidecar.assets" }, () => {
+      // Following the guide here: https://vite.dev/guide/backend-integration.html
+      const manifest = JSON.parse(readAsset(MANIFEST_NAME));
+      filesToServe[ENTRY_POINT_NAME] = readAsset(ENTRY_POINT_NAME);
+      const entries = Object.values(manifest);
+      for (const entry of entries) {
+        filesToServe[entry.file] = readAsset(entry.file);
+      }
+    });
```
Comment (betegon) [inline packages/spotlight/bin/run.js:56]: this is the kind of ting that pisses me off. this is not a change, just the formatting, but the ai decided to change it

File: packages/spotlight/bin/instrument.js (hunk 2 above)
Comment (BYK) [reply packages/spotlight/bin/instrument.js:23]: https://github.com/getsentry/sentry-javascript/blob/98de756506705b60d1ca86cbbcfad3fd76062f8f/packages/node-core/src/utils/envToBool.ts#L2

File: packages/spotlight/bin/run.js (hunk 3 above)
Comment (BYK) [reply packages/spotlight/bin/run.js:56]: I think it was reformatting, that's why I left it in.

Comment (betegon) [reply packages/spotlight/bin/run.js:56]: then perfect.

File: packages/spotlight/bin/instrument.js (hunk 2 above)
Comment (betegon) [reply packages/spotlight/bin/instrument.js:23]: 🤐
