### PR TITLE
fix(overlay): Support AI SDK in our AI view

### LINKED ISSUE #966: Support Vercel AI SDK gen_ai semantics
AI view won't work for people using new new versions of our SDKs, as they follow `gen_ai` semantics from opentelemetry and we're using `ai.` in the overlay.

### PR DESCRIPTION
**Pull request by betegon**
Closes #966

We supported AI SDK telemetry when they were in beta. Since then, they adopted [opentelemetry gen_ai semantics](https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-spans/) and our SDKs did that too. 

This PR fixes the compatibility with AI SDK.

Tool call view example: 

Screenshot 2025-10-02 at 14 29 14

### CODE REVIEW

File: packages/overlay/src/telemetry/components/insights/aiTraces/AITraceDetails.tsx [hunk 1]
```diff
@@ -215,7 +216,9 @@ function ToolCallsSection({ trace }: { trace: SpotlightAITrace }) {
 // embedded version for split view
 export function AITraceDetailsEmbedded({ traceId, spanId }: { traceId: string; spanId: string }) {
   const trace = useSentryStore(state => state.getTraceById)(traceId);
-  const span = trace?.spans.get(spanId);
+  const span = trace?.spanTree
+    ? extractAllAIRootSpans(trace.spanTree).find(({ span }) => span.span_id === spanId)?.span
+    : null;
```
Comment (betegon) [inline packages/overlay/src/telemetry/components/insights/aiTraces/AITraceDetails.tsx:221]: this change is needed as before we were being hit by "I can anaylze this trace" . 

problem was that `trace.spans.get(spanId)` ) returns the span WITHOUT children populated (i mean, just the span)

File: packages/overlay/src/telemetry/components/insights/aiTraces/AITraceDetails.tsx [hunk 2]
```diff
@@ -265,9 +268,9 @@ export function AITraceDetailsEmbedded({ traceId, spanId }: { traceId: string; s
             <span className="text-primary-400 text-sm">{aiTrace.id}</span>
           </div>
           <div className="flex items-center gap-2">
-            <Badge color="primary">{handler.getTypeBadge(aiTrace)}</Badge>
-            {aiTrace.metadata.modelId && <Badge color="secondary">{aiTrace.metadata.modelId}</Badge>}
-            {aiTrace.metadata.functionId && <Badge color="neutral">{aiTrace.metadata.functionId}</Badge>}
+            <Badge variant={aiTrace.hasToolCall ? "warning" : "primary"}>{handler.getTypeBadge(aiTrace)}</Badge>
+            {aiTrace.metadata.modelId && <Badge variant="secondary">{aiTrace.metadata.modelId}</Badge>}
+            {aiTrace.metadata.functionId && <Badge variant="neutral">{aiTrace.metadata.functionId}</Badge>}
```
Comment (betegon) [inline packages/overlay/src/telemetry/components/insights/aiTraces/AITraceDetails.tsx:273]: improved shadcn usage

File: packages/overlay/src/ui/badge.tsx [hunk 3]
```diff
@@ -4,13 +4,17 @@ import type * as React from "react";
...
     variants: {
       variant: {
         default: "border-transparent bg-primary-800 text-neutral-50",
         destructive: "border-transparent bg-red-500 text-neutral-50",
-        outline: "text-neutral-950",
+        outline: "text-neutral-950 border-neutral-200",
+        primary: "border-transparent bg-primary-800 text-neutral-50",
+        secondary: "border-transparent bg-blue-600/30 text-blue-100 border-blue-500/30",
+        neutral: "border-transparent bg-neutral-700 text-neutral-100",
+        warning: "border-transparent bg-orange-600/30 text-orange-100 border-orange-500/30",
```
Comment (betegon) [inline packages/overlay/src/ui/badge.tsx:17]: added more variants for the badges at the top of the ai view: 

Image

Image

**Comment by betegon** [comment]
@BYK yeah, although that's why I created the `AILibraryHandler` type, just in case we add more libraries in the future.

But the `vercel.` span attributes is not us but our SDKs:
 
Screenshot 2025-10-02 at 17 34 48

**Comment by BYK** [comment]
@AbhiPrasad can you help us here? ^
