### PR TITLE
fix(ui): render ANSI escape codes in log viewer

### LINKED ISSUE #1185: Spotlight logs don't parse ANSI escape codes
### Environment
Spotlight Version `4.7.1`
Sentry NestJS SDK Version `10.28.0`

### Steps to Reproduce

1. Spin up my project.
2. Log something using `Logger`, imported from `@nestjs/common`.
3. When run without spotlight, everything will be logged normally in my terminal, it will be colorful and pretty.
4. When run with spotlight enabled, it will still log normally, however the logs inside of spotlight itself look really ugly as they show the ANSI escape codes for those colors.

### Expected Result

Spotlight was either going to remove those ANSI escape codes and show text in plain colors, or actually integrate the color of the text by parsing the ANSI codes.

### Actual Result

Spotlight logs showed ANSI escape codes instead of parsing them.

### PR DESCRIPTION
**Pull request by BYK**
## Summary

Fixes #1185

Logs containing ANSI escape sequences (colors, bold, italic, etc.) are now properly styled in the UI instead of showing raw escape characters.

image

## Changes

- Added `anser` library for ANSI parsing
- Created `AnsiText` component that:
  - Parses ANSI escape codes into styled spans
  - Maps ANSI colors to Tailwind CSS classes
  - Handles formatting (bold, italic, underline, strikethrough)
- Updated `LogsList` and `LogDetail` to use the new component
- Added comprehensive unit tests for the `AnsiText` component
- Added test fixture with meaningful ANSI escape codes

## Before/After

Before: Logs showed raw escape sequences like `\u001b[32m✓\u001b[0m`
After: Logs display properly colored and formatted text

## Testing

- ✅ 9 unit tests passing for `AnsiText` component
- Tested with various ANSI color codes and formatting options

### CODE REVIEW

File: packages/spotlight/src/ui/telemetry/components/log/LogDetail.tsx [hunk 1]
```diff
@@ -25,7 +26,9 @@ export default function LogDetails({ id }: { id: string }) {
       <div className="space-y-6">
         <div>
           <h2 className="mb-2 font-bold uppercase">Message</h2>
-          <pre className="text-primary-300 whitespace-pre-wrap break-words font-mono text-sm">{body}</pre>
+          <pre className="text-primary-300 whitespace-pre-wrap break-words font-mono text-sm">
```
Comment (MathurAditya724) [inline packages/spotlight/src/ui/telemetry/components/log/LogDetail.tsx]: We can remove these text classes like text-primary-300 and maybe font-mono as those are added in the AnsiText component
