### PR TITLE
fix(overlay) : routes persistence

### LINKED ISSUE #811: Keep routing state when "minimizing" overlay
> each time i clicked out of spotlight i had to navigate back to the thing [...] we kind of wanna minimize if you will, bring it back to original state, vs "close" - @dcramer 

Imo this would be great. I think it has some relation with the ability to develop/debug your product while having spotlight aside, so you are using spotlight "live".

### PR DESCRIPTION
**Pull request by Shubhdeep12**
Fixes #811

### CODE REVIEW

**Comment by betegon** [comment]
@sentry review

**Comment by betegon** [comment]
Hey @Shubhdeep12 , I want to try out sentry review here. I'll review after that!

File: packages/overlay/src/App.tsx [hunk 1]
```diff
@@ -164,6 +166,16 @@ export default function App({
...
   // See https://github.com/remix-run/react-router/issues/7634
   const navigate = useNavigate();
+  const location = useLocation();
+
+  // contextId for namespacing of routes in sessionStorage
+  const contextId = sidecarUrl || (typeof window !== "undefined" ? window.location.origin : "default");
+
+  // helper to get valid panel routes
+  const getValidRoutes = useCallback(() => {
+    return getPanelsFromIntegrations(integrations, integrationData).map(panel => `/${panel.id}`);
```
Comment (BYK) [inline packages/overlay/src/App.tsx]: Let's convert this to a `Set()` as the main operation we do is a look up:
```suggestion
    return new Set(getPanelsFromIntegrations(integrations, integrationData).map(panel => `/${panel.id}`));
```

File: packages/overlay/src/App.tsx [hunk 2]
```diff
@@ -192,9 +204,21 @@ export default function App({
...
       log("Open");
       setOpen(true);
-      if (e.detail.path) navigate(e.detail.path);
+      if (e.detail.path) {
+        navigate(e.detail.path);
+      } else {
+        try {
+          const lastRoute = sessionStorage.getItem(getRouteStorageKey(contextId));
+          const validRoutes = getValidRoutes();
+          if (lastRoute && validRoutes.includes(lastRoute) && lastRoute !== location.pathname) {
```
Comment (BYK) [inline packages/overlay/src/App.tsx]: Based on the above, we need to use `.has` instead of `.includes`. Moreover, it makes sense to sort the comparisons in terms of cost. In this case we should check for valid route as the last step as that's the most expensive check:
```suggestion
          if (lastRoute && lastRoute !== location.pathname && validRoutes.has(lastRoute)) {
```

File: packages/overlay/src/App.tsx [hunk 3]
```diff
@@ -192,9 +204,21 @@ export default function App({
...
+            navigate(lastRoute);
+          }
+        } catch {
+          // ignore path error
```
Comment (BYK) [inline packages/overlay/src/App.tsx]: We may wanna log this into the console?

File: packages/overlay/src/App.tsx [hunk 4]
```diff
@@ -164,6 +166,16 @@ export default function App({
   // as our <Route>s are scattered around a bit
   // See https://github.com/remix-run/react-router/issues/7634
   const navigate = useNavigate();
+  const location = useLocation();
+
+  // contextId for namespacing of routes in sessionStorage
+  const contextId = sidecarUrl || (typeof window !== "undefined" ? window.location.origin : "default");
```
Comment (BYK) [inline packages/overlay/src/App.tsx]: Using `window.location.origin` is not really useful as session storage is already segregated by origin. Shall we just go with `sidecarUrl`?

File: packages/overlay/src/components/Overview.tsx [hunk 5]
```diff
@@ -11,30 +13,28 @@ export default function Overview({
...
   integrations: Integration[];
   integrationData: IntegrationData<unknown>;
   setTriggerButtonCount: (count: NotificationCount) => void;
   setOpen: (value: boolean) => void;
   isOnline: boolean;
   showClearEventsButton: boolean;
+  contextId?: string;
 }) {
   const [notificationCountSum, setNotificationCountSum] = useState<NotificationCount>({ count: 0, severe: false });
+  const location = useLocation();
```
Comment (BYK) [inline packages/overlay/src/components/Overview.tsx:28]: This (using `useLocation()`) causes a full render on each path change. We should be mindful about this. I wonder if we can hook into some higher-level React Router callback that gets triggered on each path change?

File: packages/overlay/src/components/Overview.tsx [hunk 6]
```diff
@@ -11,30 +13,28 @@ export default function Overview({
...
+    try {
+      sessionStorage.setItem(getRouteStorageKey(contextId), location.pathname);
+    } catch {
+      // ignore path error
     }
-    return [];
-  });
+  }, [location.pathname, contextId]);
+
+  const panels = getPanelsFromIntegrations(integrations, integrationData);
```
Comment (BYK) [inline packages/overlay/src/components/Overview.tsx:41]: Love the refactor here

File: packages/overlay/src/components/Overview.tsx (hunk 5 above)
Comment (Shubhdeep12) [reply packages/overlay/src/components/Overview.tsx:28]: yeah makes sense, i have an idea to resolve this issue - let me implement and push it in sometime

Comment (Shubhdeep12) [reply packages/overlay/src/components/Overview.tsx:28]: Solving this only in App.js will not help us much, as code in Overview.js and other Parent components uses these React Router hooks.
lets solve this separately

**Review by BYK — APPROVED** [review]
