### PR TITLE
fix: Added reconnect logic for sidecar in the electron app

### LINKED ISSUE #956: Electron app should be able to run when sidecar is already running
If there's already a sidecar instance running on the default port, Electron app should just connect to it and spawn its own server in the case the existing one dies for some reason.

This is in line with how we handle proxying with the `--stdio-mcp` option.

### PR DESCRIPTION
**Pull request by MathurAditya724**
Closes #956

### CODE REVIEW

File: packages/electron/src/electron/main/index.ts [hunk 1]
```diff
@@ -599,3 +593,55 @@ Promise.all([
...
+    if (subscriber) {
+      clearTimeout(subscriber);
+      subscriber = null;
+    }
+
+    if (retries >= MAX_RETRIES) {
+      return;
+    }
+
+    subscriber = setTimeout(handler, RECHECK_DELAY + retries * RETRY_DELAY_INCREMENT);
```
[the remark this answers is not in the document]
Comment (MathurAditya724) [reply packages/electron/src/electron/main/index.ts:637]: I have updated the port to DEFAULT_PORT

File: .changeset/busy-shoes-unite.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@spotlightjs/electron": patch
```
Comment (betegon) [inline .changeset/busy-shoes-unite.md]: i'd say this should be a minor. From semver:

> MINOR version when you add functionality in a backward compatible manner

File: packages/electron/src/electron/main/index.ts [hunk 3]
```diff
@@ -599,3 +593,55 @@ Promise.all([
...
+      });
+      retries = 0;
+    } catch (error) {
+      console.error(error);
+      retries++;
+
+      if (retries >= MAX_RETRIES) {
+        Sentry.captureException(error);
+
+        // Notifying the user that the sidecar is not running
```
Comment (betegon) [inline packages/electron/src/electron/main/index.ts]:
```suggestion

```

These kind of comments are a bit redundant, but LLMs love to put them. We should try to use comments to document behaviour. 

an example for this (although also redundant) that could document behaviour could be: 

> // If the sidecar isn't running, we alert the user because some features depend on it

File: packages/electron/src/electron/main/index.ts [hunk 4]
```diff
@@ -599,3 +593,55 @@ Promise.all([
...
+
+async function makeSureSidecarIsRunning() {
+  let retries = 0;
+  let subscriber: NodeJS.Timeout | null = null;
+
+  async function handler() {
+    try {
+      /**
+       * Checking if the sidecar is running
+       * And if not, starting it up
```
Comment (betegon) [inline packages/electron/src/electron/main/index.ts]: same as my comment below. if we want to add comments, comments should answer:

- Why did Aid add this? 
- Because the user could have a sidecar from another spotlight service already running
